export const GET_POKEMONS_REQUEST = 'GET_POKEMONS_REQUEST'
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS'
export const GET_POKEMONS_FAIL = 'GET_POKEMONS_FAIL'
export const SET_POKEMONS = 'SET_POKEMONS'

export const FILTER_POKEMONS = 'FILTER_POKEMONS'
export const FILTER_POKEMONS_BYHEALTH = 'FILTER_POKEMONS_BYHEALTH'
export const FILTER_POKEMONS_BYATTACK = 'FILTER_POKEMONS_BYATTACK'
export const FILTER_POKEMONS_BYDEFENCE = 'FILTER_POKEMONS_BYDEFENCE'
export const FILTER_POKEMONS_ALL = 'FILTER_POKEMONS_ALL'
export const CLEAR_POKEMONS = 'CLEAR_POKEMONS'

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'
export const SET_USERS = 'SET_USERS'

export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USERS_REQUEST'
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USERS_SUCCESS'
export const GET_CURRENT_USER_FAIL = 'GET_CURRENT_USERS_FAIL'
export const SET_CURRENT_USER = 'SET_CURRENT_USERS'
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER'

export const GET_TEAM_REQUEST = 'GET_TEAM_REQUEST'
export const SET_TEAM_REQUEST = 'SET_TEAM_REQUEST'

export const SET_IDOLD_REQUEST = 'SET_IDOLD_REQUEST'
export const SET_IDOLD = 'SET_IDOLD'
export const CLEAR_IDOLD = 'CLEAR_IDOLD'

