// Generated by https://quicktype.io

export interface PokemonModel {
    id:   number;
    name: Name;
    type: string[];
    base: Base;
}

export interface Base {
    HP:        number;
    Attack:    number;
    Defense:   number;
    SpAttack:  number;
    SpDefense: number;
    Speed:     number;
}

export interface Name {
    english:  string;
    japanese: string;
    chinese:  string;
}
